version: '3'

services:
  postgres: 
    image: 'postgres:11.4-alpine'
  redis:
    image: 'redis:5.0.5-alpine'
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '3051:80'
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./api
    volumes: 
      - /app/node_modules
      - ./api:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
    depends_on: 
      - postgres
      - redis
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /app/node_modules
      - ./worker:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on: 
      - redis
    
  
    
    